#
# MongoDB Dockerfile
#
# https://github.com/suzhugen/mongo
#

# Pull base image.
FROM ubuntu:xenial

# Install MongoDB.

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | tee "/etc/apt/sources.list.d/mongodb-org-3.6.list"


RUN \
  apt-get update  \
  && apt-get install -y mongodb-org=3.6.0  \
  && rm -rf /var/lib/apt/lists/*

# Define mountable directories.
VOLUME ["/data/db"]


# Define working directory.
WORKDIR /data

COPY mongod-all-ips.conf  /etc/mongod.conf

# Define default command.
CMD ["mongod","--auth"]

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017

