#
# MongoDB Dockerfile
#
# https://github.com/suzhugen/mongo
#

# Pull base image.
FROM ubuntu:xenial

# Install MongoDB.
# Allow build-time overrides (eg. to build image with MongoDB Enterprise version)
# Options for MONGO_PACKAGE: mongodb-org OR mongodb-enterprise
# Options for MONGO_REPO: repo.mongodb.org OR repo.mongodb.com
# Example: docker build --build-arg MONGO_PACKAGE=mongodb-enterprise --build-arg MONGO_REPO=repo.mongodb.com .
ARG MONGO_PACKAGE=mongodb-org
ARG MONGO_REPO=repo.mongodb.org
ENV MONGO_PACKAGE=${MONGO_PACKAGE} MONGO_REPO=${MONGO_REPO}

ENV MONGO_MAJOR 3.6
ENV MONGO_VERSION 3.6.0

RUN echo "deb http://$MONGO_REPO/apt/ubuntu/xenial/mongodb-org/3.6/Release" | tee "/etc/apt/sources.list.d/${MONGO_PACKAGE%-unstable}.list"


RUN \
  apt-get update  \
  && apt-get install -y \
		${MONGO_PACKAGE}=$MONGO_VERSION \
		${MONGO_PACKAGE}-server=$MONGO_VERSION \
		${MONGO_PACKAGE}-shell=$MONGO_VERSION \
		${MONGO_PACKAGE}-mongos=$MONGO_VERSION \
		${MONGO_PACKAGE}-tools=$MONGO_VERSION \
  && rm -rf /var/lib/apt/lists/*

# Define mountable directories.
VOLUME ["/data/db"]


# Define working directory.
WORKDIR /data

COPY mongod-all-ips.conf  /etc/mongod.conf

# Define default command.
CMD ["mongod","--auth"]

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017

